### ISSUE TITLE
Great, way to go!

### ISSUE THREAD

**Issue by artelse** [pdincubus/MODX-Revolution-Responsive-Manager-Theme#1]
The issue I have is with the current manager which is a dud. Time and again am so happy when I need to work on an older Evo site. Way to go, hope it will be implemented as it looks so much better already. I also hope it will be efficiently hand coded like Evo!

**Comment by pdincubus** [comment]
Thanks for kind comments :)

I think MODX3 is a fair way off yet and sounds like will be a pretty monumental change in a lot of aspects of the system... I'm looking forward to it!
