### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by vierkantemeter** [pdincubus/MODX-Revolution-Responsive-Manager-Theme#4]
Hi, your theme looks great! Is it still in development? Is there a working version?

**Comment by pdincubus** [comment]
You can see a static sort-of doing stuff mockup here: http://pdincubus.github.io/MODX-Revolution-Responsive-Manager-Theme/2/ It's not an actual MODX manager theme as how the manager currently works won't allow for it!

**Comment by vierkantemeter** [comment]
Yeah I saw the mockup, looks excellent! Didn't realize it's not possible to implement it, bummer!

**Comment by pdincubus** [comment]
They are currently running this: http://a11y.modx.com/
Which aims to make it more accessible - and in doing so I'd imagine that it would allow for much better theming/manager general markup but feels like that will take a reasonably long time to do.

**Comment by vierkantemeter** [comment]
Yes that's a great initiative, already donated some money but I see they're not quite there yet. We'll see what happens, hopefully you'll be able to create your theme when the accessible manager is there.
